# Generated by Django 4.0.6 on 2022-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blenderModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('catagory', models.CharField(blank=True, choices=[('PLANET', 'planet'), ('SHIP', 'ship'), ('BUILDING', 'building'), ('OBJECT', 'object')], max_length=50, null=True)),
                ('image', models.ImageField(upload_to='static/images')),
                ('description', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blender Models',
            },
        ),
    ]
