# Generated by Django 4.0.6 on 2022-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlenderModeling', '0002_blendermodels_video_alter_blendermodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendermodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images'),
        ),
    ]
