# Generated by Django 4.0.6 on 2022-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchstreaming',
            name='catagory',
            field=models.CharField(blank=True, choices=[('ACTION', 'action'), ('SURVIVAL', 'survival'), ('MMORPG', 'mmorpg'), ('ADVENTURE', 'adventure'), ('STRATAGY', 'stratagy')], max_length=50, null=True),
        ),
    ]
