# Generated by Django 4.0.6 on 2022-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0002_electronicsprojects_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsprojects',
            name='catagory',
            field=models.CharField(blank=True, choices=[('RASPBERRY PI', 'raspberry pi'), ('CIRCUIT', 'circuit'), ('ROBOTICS', 'robotics'), ('GADGETS', 'gadgets')], max_length=50, null=True),
        ),
    ]
